[character]
success_symbol = "[ğŸ”­ â¯](bold green)"
error_symbol = "[ğŸ”­ âœ—](bold red)"
vicmd_symbol = "[ğŸ”­ â¯](bold blue)"

[python]
format = '[${symbol} ${pyenv_prefix}(\($virtualenv\))]($style)'
symbol = "î˜†"

[gcloud]
disabled = true

[package]
disabled = true

[git_branch]
style = "bold purple"
