[character]
success_symbol = "[ğŸ”­ â¯](bold green)"
error_symbol = "[ğŸ”­ â¯](bold red)"
vicmd_symbol = "[ğŸ”­ â¯](bold blue)"

[python]
symbol = "î˜†"
disabled= true

[gcloud]
disabled = true

[package]
disabled = true

[git_branch]
style = "bold purple"
